{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "libravdbd.fullname" . }}-tls
  labels:
    {{- include "libravdbd.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
  {{- if .Values.tls.ca }}
  ca.crt: {{ .Values.tls.ca }}
  {{- end }}
{{- end }}
